sudo: required
dist: trusty
language: cpp
cache: apt

before_install:
 - sudo apt-add-repository -y ppa:beineri/opt-qt56-trusty
 - sudo apt-get update -qq

install:
 - sudo apt-get install -q qt56base qt56tools qt56webengine

script:
 - /opt/qt56/bin/qmake PREFIX=/app/
 - bash -ex appimage.sh
