sudo: required
dist: trusty
language: cpp
cache: apt

before_install:
 - sudo sed -i -e 's|http://us.archive.ubuntu.com/ubuntu/|http://eu-central-1.clouds.archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list
 - sudo apt-add-repository -y ppa:beineri/opt-qt56-trusty
 - sudo apt-get update

install:
 - sudo apt-get install -y qt56base qt56tools qt56webengine

script:
 - /opt/qt56/bin/qmake PREFIX=/app/
 - bash -ex appimage.sh
